# === DO_NOT_EDIT: pkg-ext site ===
site_name: ask_shell
# === OK_EDIT: pkg-ext site ===

# === DO_NOT_EDIT: pkg-ext theme ===
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
# === OK_EDIT: pkg-ext theme ===

# === DO_NOT_EDIT: pkg-ext nav ===
nav:
  - Home: index.md
  - ask_shell:
    - Overview: _root/index.md
    - AskShellSettings: _root/askshellsettings.md
  - ask:
    - Overview: ask/index.md
    - RaiseOnQuestionError: ask/raiseonquestionerror.md
    - SelectOptions: ask/selectoptions.md
    - question_patcher: ask/question_patcher.md
    - raise_on_question: ask/raise_on_question.md
  - console: console/index.md
  - shell:
    - Overview: shell/index.md
    - ShellConfig: shell/shellconfig.md
    - ShellError: shell/shellerror.md
    - run: shell/run.md
    - run_and_wait: shell/run_and_wait.md
  - shell_events: shell_events/index.md
# === OK_EDIT: pkg-ext nav ===

# === DO_NOT_EDIT: pkg-ext extensions ===
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - attr_list
# === OK_EDIT: pkg-ext extensions ===
